version: "3"

networks:
  kafka-nt:
    name: kafka-cluster

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:$ZTAG
    container_name: zookeeper
    user: "0:0"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - $PWD/data/zp:/bitnami/zookeeper
    networks:
      - kafka-nt
    ports:
      - $ZPORT:$ZPORT
