version: "3"

networks:
  kafka-nt:
    name: kafka-cluster

services:
  kafka:
    image: docker.io/bitnami/kafka:$KTAG
    container_name: kafka
    user: "0:0"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=$ZHOST:$ZPORT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_BROKER_ID=$KID
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:$KPORT1,EXTERNAL://:$KPORT2
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://$KHOST:$KPORT1,EXTERNAL://$KHOST:$KPORT2
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - $PWD/data/kafka:/bitnami/kafka
    networks:
      - kafka-nt
    ports:
      - $KPORT1:$KPORT1
      - $KPORT2:$KPORT2
